package com.rongyi.easy.msgcenter;

import java.io.Serializable;
import java.util.Date;

public class TriggerActivityParam  implements Serializable{
 	private String userId;
    public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

 
	private String shopId;
 
	public String getShopId() {
		return shopId;
	}

	public void setShopId(String shopId) {
		this.shopId = shopId;
	}
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trigger_activity.id
     *
     * @mbggenerated Wed Mar 30 17:22:50 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trigger_activity.push_activity_id
     *
     * @mbggenerated Wed Mar 30 17:22:50 CST 2016
     */
    private Integer pushActivityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trigger_activity.push_condition
     *1:注册，2交易，3邀请，4激活
     * @mbggenerated Wed Mar 30 17:22:50 CST 2016
     */
    private Byte pushCondition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trigger_activity.trade_category
     *'交易品类;“1,2”，1商品，2卡券',
     * @mbggenerated Wed Mar 30 17:22:50 CST 2016
     */
    private String tradeCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trigger_activity.trade_times
     *交易频次,
     * @mbggenerated Wed Mar 30 17:22:50 CST 2016
     */
    private Integer tradeTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trigger_activity.trade_amount
     * 交易区间开始-结束金额值
     * @mbggenerated Wed Mar 30 17:22:50 CST 2016
     */
    private Integer tradeStartAmount;
    private Integer tradeEndtAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trigger_activity.trade_range
     *交易范围：1全部，2品牌，3商城，4店铺'
     * @mbggenerated Wed Mar 30 17:22:50 CST 2016
     */
    private Byte tradeRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trigger_activity.obtain_times
     *
     * @mbggenerated Wed Mar 30 17:22:50 CST 2016
     */
    private Byte obtainTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trigger_activity.invite
     *
     * @mbggenerated Wed Mar 30 17:22:50 CST 2016
     */
    private Byte invite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trigger_activity.fruitful
     *
     * @mbggenerated Wed Mar 30 17:22:50 CST 2016
     */
    private Byte fruitful;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trigger_activity.fruitful_range
     *
     * @mbggenerated Wed Mar 30 17:22:50 CST 2016
     */
    private Byte fruitfulRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trigger_activity.not_activate_day
     *
     * @mbggenerated Wed Mar 30 17:22:50 CST 2016
     */
    private Integer notActivateDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trigger_activity.not_consumer_day
     *
     * @mbggenerated Wed Mar 30 17:22:50 CST 2016
     */
    private Integer notConsumerDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trigger_activity.start_at
     *
     * @mbggenerated Wed Mar 30 17:22:50 CST 2016
     */
    private Date startAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trigger_activity.end_at
     *
     * @mbggenerated Wed Mar 30 17:22:50 CST 2016
     */
    private Date endAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trigger_activity.id
     *
     * @return the value of trigger_activity.id
     *
     * @mbggenerated Wed Mar 30 17:22:50 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trigger_activity.id
     *
     * @param id the value for trigger_activity.id
     *
     * @mbggenerated Wed Mar 30 17:22:50 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trigger_activity.push_activity_id
     *
     * @return the value of trigger_activity.push_activity_id
     *
     * @mbggenerated Wed Mar 30 17:22:50 CST 2016
     */
    public Integer getPushActivityId() {
        return pushActivityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trigger_activity.push_activity_id
     *
     * @param pushActivityId the value for trigger_activity.push_activity_id
     *
     * @mbggenerated Wed Mar 30 17:22:50 CST 2016
     */
    public void setPushActivityId(Integer pushActivityId) {
        this.pushActivityId = pushActivityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trigger_activity.push_condition
     *
     * @return the value of trigger_activity.push_condition
     *
     * @mbggenerated Wed Mar 30 17:22:50 CST 2016
     */
    public Byte getPushCondition() {
        return pushCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trigger_activity.push_condition
     *
     * @param pushCondition the value for trigger_activity.push_condition
     *
     * @mbggenerated Wed Mar 30 17:22:50 CST 2016
     */
    public void setPushCondition(Byte pushCondition) {
        this.pushCondition = pushCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trigger_activity.trade_category
     *
     * @return the value of trigger_activity.trade_category
     *
     * @mbggenerated Wed Mar 30 17:22:50 CST 2016
     */
    public String getTradeCategory() {
        return tradeCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trigger_activity.trade_category
     *
     * @param tradeCategory the value for trigger_activity.trade_category
     *
     * @mbggenerated Wed Mar 30 17:22:50 CST 2016
     */
    public void setTradeCategory(String tradeCategory) {
        this.tradeCategory = tradeCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trigger_activity.trade_times
     *
     * @return the value of trigger_activity.trade_times
     *
     * @mbggenerated Wed Mar 30 17:22:50 CST 2016
     */
    public Integer getTradeTimes() {
        return tradeTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trigger_activity.trade_times
     *
     * @param tradeTimes the value for trigger_activity.trade_times
     *
     * @mbggenerated Wed Mar 30 17:22:50 CST 2016
     */
    public void setTradeTimes(Integer tradeTimes) {
        this.tradeTimes = tradeTimes;
    }

  

    public Integer getTradeStartAmount() {
		return tradeStartAmount;
	}

	public void setTradeStartAmount(Integer tradeStartAmount) {
		this.tradeStartAmount = tradeStartAmount;
	}

	public Integer getTradeEndtAmount() {
		return tradeEndtAmount;
	}

	public void setTradeEndtAmount(Integer tradeEndtAmount) {
		this.tradeEndtAmount = tradeEndtAmount;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trigger_activity.trade_range
     *
     * @return the value of trigger_activity.trade_range
     *
     * @mbggenerated Wed Mar 30 17:22:50 CST 2016
     */
    public Byte getTradeRange() {
        return tradeRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trigger_activity.trade_range
     *
     * @param tradeRange the value for trigger_activity.trade_range
     *
     * @mbggenerated Wed Mar 30 17:22:50 CST 2016
     */
    public void setTradeRange(Byte tradeRange) {
        this.tradeRange = tradeRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trigger_activity.obtain_times
     *
     * @return the value of trigger_activity.obtain_times
     *
     * @mbggenerated Wed Mar 30 17:22:50 CST 2016
     */
    public Byte getObtainTimes() {
        return obtainTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trigger_activity.obtain_times
     *
     * @param obtainTimes the value for trigger_activity.obtain_times
     *
     * @mbggenerated Wed Mar 30 17:22:50 CST 2016
     */
    public void setObtainTimes(Byte obtainTimes) {
        this.obtainTimes = obtainTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trigger_activity.invite
     *
     * @return the value of trigger_activity.invite
     *
     * @mbggenerated Wed Mar 30 17:22:50 CST 2016
     */
    public Byte getInvite() {
        return invite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trigger_activity.invite
     *
     * @param invite the value for trigger_activity.invite
     *
     * @mbggenerated Wed Mar 30 17:22:50 CST 2016
     */
    public void setInvite(Byte invite) {
        this.invite = invite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trigger_activity.fruitful
     *
     * @return the value of trigger_activity.fruitful
     *
     * @mbggenerated Wed Mar 30 17:22:50 CST 2016
     */
    public Byte getFruitful() {
        return fruitful;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trigger_activity.fruitful
     *
     * @param fruitful the value for trigger_activity.fruitful
     *
     * @mbggenerated Wed Mar 30 17:22:50 CST 2016
     */
    public void setFruitful(Byte fruitful) {
        this.fruitful = fruitful;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trigger_activity.fruitful_range
     *
     * @return the value of trigger_activity.fruitful_range
     *
     * @mbggenerated Wed Mar 30 17:22:50 CST 2016
     */
    public Byte getFruitfulRange() {
        return fruitfulRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trigger_activity.fruitful_range
     *
     * @param fruitfulRange the value for trigger_activity.fruitful_range
     *
     * @mbggenerated Wed Mar 30 17:22:50 CST 2016
     */
    public void setFruitfulRange(Byte fruitfulRange) {
        this.fruitfulRange = fruitfulRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trigger_activity.not_activate_day
     *
     * @return the value of trigger_activity.not_activate_day
     *
     * @mbggenerated Wed Mar 30 17:22:50 CST 2016
     */
    public Integer getNotActivateDay() {
        return notActivateDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trigger_activity.not_activate_day
     *
     * @param notActivateDay the value for trigger_activity.not_activate_day
     *
     * @mbggenerated Wed Mar 30 17:22:50 CST 2016
     */
    public void setNotActivateDay(Integer notActivateDay) {
        this.notActivateDay = notActivateDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trigger_activity.not_consumer_day
     *
     * @return the value of trigger_activity.not_consumer_day
     *
     * @mbggenerated Wed Mar 30 17:22:50 CST 2016
     */
    public Integer getNotConsumerDay() {
        return notConsumerDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trigger_activity.not_consumer_day
     *
     * @param notConsumerDay the value for trigger_activity.not_consumer_day
     *
     * @mbggenerated Wed Mar 30 17:22:50 CST 2016
     */
    public void setNotConsumerDay(Integer notConsumerDay) {
        this.notConsumerDay = notConsumerDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trigger_activity.start_at
     *
     * @return the value of trigger_activity.start_at
     *
     * @mbggenerated Wed Mar 30 17:22:50 CST 2016
     */
    public Date getStartAt() {
        return startAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trigger_activity.start_at
     *
     * @param startAt the value for trigger_activity.start_at
     *
     * @mbggenerated Wed Mar 30 17:22:50 CST 2016
     */
    public void setStartAt(Date startAt) {
        this.startAt = startAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trigger_activity.end_at
     *
     * @return the value of trigger_activity.end_at
     *
     * @mbggenerated Wed Mar 30 17:22:50 CST 2016
     */
    public Date getEndAt() {
        return endAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trigger_activity.end_at
     *
     * @param endAt the value for trigger_activity.end_at
     *
     * @mbggenerated Wed Mar 30 17:22:50 CST 2016
     */
    public void setEndAt(Date endAt) {
        this.endAt = endAt;
    }

	@Override
	public String toString() {
		return "TriggerActivity [userId=" + userId + ", shopId=" + shopId
				+ ", id=" + id + ", pushActivityId=" + pushActivityId
				+ ", pushCondition=" + pushCondition + ", tradeCategory="
				+ tradeCategory + ", tradeTimes=" + tradeTimes
				+ ", tradeStartAmount=" + tradeStartAmount
				+ ", tradeEndtAmount=" + tradeEndtAmount + ", tradeRange="
				+ tradeRange + ", obtainTimes=" + obtainTimes + ", invite="
				+ invite + ", fruitful=" + fruitful + ", fruitfulRange="
				+ fruitfulRange + ", notActivateDay=" + notActivateDay
				+ ", notConsumerDay=" + notConsumerDay + ", startAt=" + startAt
				+ ", endAt=" + endAt + "]";
	}

 

 
    
}